type Organization {
  id: ID!
  name: String!
  slug: String!
  plan: String!
  createdAt: String!
  updatedAt: String!
}

type User {
  id: ID!
  orgId: ID!
  name: String!
  email: String!
  role: String!
  isEmailVerified: Boolean!
  lastLogin: String
  createdAt: String!
}

type AuthPayload {
  token: String!
  user: User!
  org: Organization!
  message: String
}

input RegisterInput {
  name: String!
  email: String!
  password: String!
  orgName: String!
}

type Query {
  me: User!
}

type Mutation {
  register(input: RegisterInput!): AuthPayload!
  login(email: String!, password: String!): AuthPayload!
}
